openapi: 3.1.1
info:
  title: Banking Service API
  version: 1.0.0
paths:
  /accounts:
    post:
      summary: Add an account to the bank.
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        "200":
          description: Account added.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /accounts/{accountId}:
    get:
      summary: Retrieve an account by its unique ID.
      operationId: getAccount
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        "200":
          description: Account found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: Account not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      delete:
        summary: Remove an account by its unique ID.
        operationId: removeAccount
        parameters:
          - $ref: "#/components/parameters/AccountId"
        responses:
          "200":
            description: Account removed.
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Account"
          "404":
            description: Account not found.
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /accounts/{accountId}/balance:  
    get:
      summary: Retrieve the balance of an account.
      operationId: getBalance
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        "200":
          description: Account balance retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: float
        "404":
          description: Account not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /accounts/{accountId}/deposit:
    post:
      summary: Deposit money into an account.
      operationId: depositFunds
      parameters:
        - $ref: "#/components/parameters/AccountId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
      responses:
        "200":
          description: Money deposited successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /accounts/{accountId}/withdraw:
    post:
      summary: Withdraw money from an account.
      operationId: withdrawFunds
      parameters:
        - $ref: "#/components/parameters/AccountId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
      responses:
        "200":
          description: Money withdrawn successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"